git:
  quiet: true
  submodules: true
  depth: 50

language: java
jdk:
  - oraclejdk8

before_install:
  - "chmod +x gradlew"

install:
  - "./gradlew cleanLoomBinaries cleanLoomMappings clean"

script:
  - "./gradlew build"

before_cache:
  - find $HOME/.gradle/ -name '*.lock' -print -exec rm -f {} \;

cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"

before_deploy:
  - echo "Deploying to NerdHub Maven"

deploy:
  -   provider: script
      script: "./gradlew publish"
      skip_cleanup: true
      on:
        repo: NerdHubMC/Trinkets
        branch: master

  # if commit tag is created, deploy to curseforge
  -   provider: script
      script: "./gradlew curseforge"
      target_commitsh: $TRAVIS_TAG
      skip_cleanup: true
      on:
        repo: NerdHubMC/Trinkets
        tags: true
        branch: master
